import { createTool } from '@mastra/core/tools';
import { z } from 'zod';
import { embedText } from '../../lib/embeddings.js';
import { getQdrantClient } from '../../lib/qdrant.js';
import { v4 as uuidv4 } from 'uuid';

const CACHE_COLLECTION = 'semantic_cache';

// ─── Cache Check Tool ─────────────────────────────────────────────────────────

export const semanticCacheCheckTool = createTool({
  id: 'semantic-cache-check',
  description: 'Searches Qdrant semantic_cache for an exact or near-exact match of the incoming alert. If found and recent, short-circuits LLM generation.',
  inputSchema: z.object({
    payload: z.string().describe('The raw or sanitized alert payload to check against cache'),
  }),
  outputSchema: z.object({
    cacheHit: z.boolean(),
    cachedPlanId: z.string().optional(),
    cachedPlan: z.any().optional(),
    similarityScore: z.number().optional(),
  }),
  execute: async ({ payload }) => {
    try {
      const qdrant = getQdrantClient();
      const denseVector = await embedText(payload);
      
      const searchResponse = await qdrant.search(CACHE_COLLECTION, {
        vector: denseVector,
        limit: 1,
        with_payload: true,
      });

      if (searchResponse.length > 0) {
        const bestHit = searchResponse[0];
        // 0.98 is a very high threshold, meaning essentially the exact same alert (e.g. from an alert storm)
        if (bestHit.score > 0.98) {
          return {
            cacheHit: true,
            cachedPlanId: String(bestHit.id),
            cachedPlan: bestHit.payload?.remediation_plan,
            similarityScore: bestHit.score,
          };
        }
      }

      return { cacheHit: false };
    } catch (err) {
      console.error('Semantic Cache Check failed (Qdrant error):', err);
      // Fail open: if cache is unreachable, assume cache miss and proceed normally
      return { cacheHit: false };
    }
  },
});

// ─── Cache Write Tool ─────────────────────────────────────────────────────────

export const semanticCacheWriteTool = createTool({
  id: 'semantic-cache-write',
  description: 'Writes a successfully generated remediation plan to the Qdrant semantic_cache to short-circuit future identical alerts.',
  inputSchema: z.object({
    payload: z.string().describe('The raw or sanitized alert payload that triggered this plan'),
    remediationPlan: z.any().describe('The final Remediation Plan generated by the LLM'),
  }),
  outputSchema: z.object({
    success: z.boolean(),
    cacheId: z.string().optional(),
  }),
  execute: async ({ payload, remediationPlan }) => {
    try {
      const qdrant = getQdrantClient();
      const denseVector = await embedText(payload);
      const cacheId = uuidv4();

      await qdrant.upsert(CACHE_COLLECTION, {
        wait: true,
        points: [
          {
            id: cacheId,
            vector: denseVector,
            payload: {
              remediation_plan: remediationPlan,
              original_payload: payload,
              cached_at: new Date().toISOString(),
            },
          },
        ],
      });

      return { success: true, cacheId };
    } catch (err) {
      console.error('Semantic Cache Write failed:', err);
      return { success: false };
    }
  },
});
